### ISSUE TITLE
Got these error after starting

### ISSUE THREAD

**Issue by JoeGhost-22** [ferelarg/Seplos3MQTT#6]
Hello, I followed your video, I got the image running in a stack in portainer. But there are no topic send, looks like no mqtt connection is established.
Also I dont know where to place the ini file. Which directory should be used?
Here is the error log after starting it.

2024-04-07 18:09:07,533 Opening serial interface, port: /dev/ttyUSB0 19200 8N1 timeout: 0.001750
Exception ignored in: <function Client.__del__ at 0x7f8907e040>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
 
Unexpected error: __init__() missing 1 required positional argument: 'callback_api_version'
Usage:
  python seplos3mqtt.py
Seplos3mqtt gets the configuration from seplos3mqtt.ini
Remember to create the file and include the following data:
[seplos3mqtt]
serial = 
mqtt_server = 
mqtt_port = 
mqtt_user = 
mqtt_pass = 
mqtt_prefix = 

Can you please help me?
Thank you

**Comment by JoeGhost-22** [comment]
solved by bagges. thank you very much Markus
